
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Oct 11 18:09:48 CST 2018
//----------------------------------------------------

package lexicalanalyzerc;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int lParenthesis = 9;
  public static final int BRACKETS = 51;
  public static final int READINT_KW = 44;
  public static final int INTERFACE = 18;
  public static final int doubleConstants = 55;
  public static final int GETBYTE_M = 48;
  public static final int FOR = 21;
  public static final int MINUS = 29;
  public static final int comma = 12;
  public static final int NOT = 41;
  public static final int AND = 39;
  public static final int rParenthesis = 10;
  public static final int boolConstantType = 5;
  public static final int SETBYTE_M = 49;
  public static final int EQUALTO = 37;
  public static final int OR = 40;
  public static final int CLASS = 13;
  public static final int intConstantType = 3;
  public static final int DIV = 31;
  public static final int NEWARRAY_KW = 43;
  public static final int PLUS = 28;
  public static final int IF = 19;
  public static final int THIS = 27;
  public static final int rBracket = 8;
  public static final int MORET = 35;
  public static final int booleanConstants = 56;
  public static final int NOEQUAL = 38;
  public static final int EOF = 0;
  public static final int ident = 52;
  public static final int RETURN = 23;
  public static final int EQUAL = 26;
  public static final int error = 1;
  public static final int NULL = 50;
  public static final int READLINE_KW = 45;
  public static final int MOD = 32;
  public static final int BREAK = 24;
  public static final int VOID = 11;
  public static final int stringConstantType = 6;
  public static final int point = 47;
  public static final int MORETE = 36;
  public static final int LESSTE = 34;
  public static final int TIMES = 30;
  public static final int NEW_KW = 42;
  public static final int ELSE = 20;
  public static final int WHILE = 22;
  public static final int MALLOC_KW = 46;
  public static final int EXTENDS = 14;
  public static final int doubleConstantType = 4;
  public static final int lBrace = 15;
  public static final int LESST = 33;
  public static final int IMPLEMENTS = 17;
  public static final int semicolon = 2;
  public static final int rBrace = 16;
  public static final int lBracket = 7;
  public static final int PRINT = 25;
  public static final int stringConstants = 53;
  public static final int integerConstants = 54;
}

